/**
 * Built-in systems — committed to the repo so data persists on every deploy.
 * Edit this file to change names, URLs, or credentials.
 */
export const BUILTIN_SYSTEMS = [
  {
    id: "system-hr",
    name: "إدارة الموارد البشرية",
    nameEn: "Human Resources",
    frontendUrl: "https://hr.cmfsa-iq.com",
    backendUrl: "https://hr-api.cmfsa-iq.com/api/Auth/Login",
    url: "https://hr-api.cmfsa-iq.com/api/Auth/Login",
    requiresAuth: true,
    auth: {
      phoneNumber: "0",
      password: "0",
      monitorLogin: true,
    },
  },
  {
    id: "system-cds",
    name: "نظام التوزيع الوظيفي",
    nameEn: "Job Distribution System",
    frontendUrl: "http://cds-cmfsa.duckdns.org/dashboard/login",
    backendUrl: "",
    url: "http://cds-cmfsa.duckdns.org/dashboard/login",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-health-services",
    name: "نظام الخدمات الصحية",
    nameEn: "Health Services System",
    frontendUrl: "https://services.cmfsa-iq.com",
    backendUrl: "https://services-api.cmfsa-iq.com/Auth/GetUsers",
    url: "https://services-api.cmfsa-iq.com/Auth/GetUsers",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-assets",
    name: "نظام الأصول",
    nameEn: "Assets System",
    frontendUrl: "https://asset.cmfsa-iq.com",
    backendUrl: "https://asset-api.cmfsa-iq.com/api/Auth/Login",
    url: "https://asset-api.cmfsa-iq.com/api/Auth/Login",
    requiresAuth: true,
    auth: {
      phoneNumber: "0",
      password: "0",
      monitorLogin: true,
    },
  },
  {
    id: "system-medication",
    name: "نظام إدارة المخازن",
    nameEn: "Medication / Warehouse System",
    frontendUrl: "https://medication.cmfsa-iq.com",
    backendUrl: "https://api-medication.cmfsa-iq.com/api/Auth/Login",
    url: "https://api-medication.cmfsa-iq.com/api/Auth/Login",
    requiresAuth: true,
    auth: {
      phoneNumber: "0",
      password: "0",
      monitorLogin: true,
    },
  },
  {
    id: "system-vacation",
    name: "نظام الإجازات",
    nameEn: "Vacation System",
    frontendUrl: "https://vacation.cmfsa-iq.com",
    backendUrl: "https://vacation-api.cmfsa-iq.com/api/Users/login",
    url: "https://vacation-api.cmfsa-iq.com/api/Users/login",
    requiresAuth: true,
    auth: {
      phoneNumber: "2",
      password: "2",
      loginStyle: "pascal",
      monitorLogin: true,
    },
  },
  {
    id: "system-crowd-medicine",
    name: "موقع طب الحشود",
    nameEn: "Crowd Medicine Website",
    frontendUrl: "https://int-mgm.org/index",
    backendUrl: "",
    url: "https://int-mgm.org/index",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-media",
    name: "موقع الإعلام",
    nameEn: "Media Website",
    frontendUrl: "http://cmfsa-iq.com",
    backendUrl: "",
    url: "http://cmfsa-iq.com",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-health-media",
    name: "موقع إعلام الخدمات الصحية",
    nameEn: "Health Services Media",
    frontendUrl: "https://healthservicesdir.com",
    backendUrl: "",
    url: "https://healthservicesdir.com",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-tayid",
    name: "نظام التأييدات",
    nameEn: "Endorsements System",
    frontendUrl: "https://tayid.cmfsa-iq.com",
    backendUrl: "https://tayid-api.cmfsa-iq.com/api/Dashboard",
    url: "https://tayid-api.cmfsa-iq.com/api/Dashboard",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-pb",
    name: "نظام الخدج",
    nameEn: "PB System",
    frontendUrl: "https://pb.cmfsa-iq.com",
    backendUrl: "https://pb-api.cmfsa-iq.com/swagger",
    url: "https://pb-api.cmfsa-iq.com/swagger",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-medical",
    name: "النظام الطبي",
    nameEn: "Medical System",
    frontendUrl: "https://dashboard-medicalpoint.cmfsa-iq.com/",
    backendUrl: "https://medical-api.cmfsa-iq.com/api/Dashbord/GetDashboardCounts",
    url: "https://medical-api.cmfsa-iq.com/api/Dashbord/GetDashboardCounts",
    requiresAuth: true,
    auth: {
      
      phoneNumber: "ghafar",
      password: "1212",
    },
  },
  {
    id: "system-empform",
    name: "نظام استمارة الموظف",
    nameEn: "Employee Form System",
    frontendUrl: "https://empform.cmfsa-iq.com",
    backendUrl: "https://empform-api.cmfsa-iq.com/Auth/DashboardCount",
    url: "https://empform-api.cmfsa-iq.com/Auth/DashboardCount",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
  {
    id: "system-medicalpoint",
    name: "تطبيق الاحصائي",
    nameEn: "Statistical Application",
    frontendUrl: "https://app-medicalpoint.cmfsa-iq.com/",
    backendUrl: "",
    url: "https://app-medicalpoint.cmfsa-iq.com/",
    requiresAuth: false,
    auth: { phoneNumber: "", password: "" },
  },
];

export const BUILTIN_SYSTEM_IDS = new Set(BUILTIN_SYSTEMS.map((s) => s.id));
